# yaml-language-server: $schema=../vendor/symfony/dependency-injection/Loader/schema/services.schema.json

parameters:
    uploads_directory: '%kernel.project_dir%/public/medias'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'

    App\Service\FormationApercuStorage:
        arguments:
            $projectDir: '%kernel.project_dir%'
            $uploadsDirectory: '%uploads_directory%'

    App\Service\AttestationPdfGenerator:
        arguments:
            $projectDir: '%kernel.project_dir%'

    App\Command\TestAttestationPdfCommand:
        arguments:
            $projectDir: '%kernel.project_dir%'

    App\Service\MailerConfig:
        arguments:
            $mailerDsn: '%env(MAILER_DSN)%'
            $mailerFrom: '%env(MAILER_FROM)%'
            $mailerFromName: '%env(MAILER_FROM_NAME)%'
